--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/arbuz/Pictures/Wallpapers/22.jpg"

-- Special
background="#0d0d0d"
foreground="#d6d7da"
cursor="#d6d7da"

-- Colors
color0="#0d0d0d"
color1="#7D8188"
color2="#8B8E95"
color3="#989BA3"
color4="#9EA1A7"
color5="#ACAEB4"
color6="#B9BCC2"
color7="#d6d7da"
color8="#959698"
color9="#7D8188"
color10="#8B8E95"
color11="#989BA3"
color12="#9EA1A7"
color13="#ACAEB4"
color14="#B9BCC2"
color15="#d6d7da"
