# Shell variables
# Generated by 'wal'
wallpaper='/home/arbuz/Pictures/Wallpapers/22.jpg'

# Special
background='#0d0d0d'
foreground='#d6d7da'
cursor='#d6d7da'

# Colors
color0='#0d0d0d'
color1='#7D8188'
color2='#8B8E95'
color3='#989BA3'
color4='#9EA1A7'
color5='#ACAEB4'
color6='#B9BCC2'
color7='#d6d7da'
color8='#959698'
color9='#7D8188'
color10='#8B8E95'
color11='#989BA3'
color12='#9EA1A7'
color13='#ACAEB4'
color14='#B9BCC2'
color15='#d6d7da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
